title: Adv. Prog. (C++)
description: Advanced Programming with C++
theme: just-the-docs
author: M. Amintoosi

url: https://fum-cs.github.io/AdvProg-CPP

aux_links:
  CS Dept.:
    - 'https://fumcs.github.io'
  Mahmood Amintoosi:
    - 'https://mamintoosi.github.io'
  Modern C++:
    - 'https://github.com/fum-cs/modern-cpp'
  Class Repository:
    - 'https://github.com/fum-cs/AdvProg-CPP'